apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: aroundu
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: aroundu
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
